name: Release App
on:
  push:
    tags: ["*"]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-logger-ui

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      docker:
        image: myjettools/dioxus-alpha:0.1.0
        options: --privileged
        ports:
          - 2375:2375    
    steps:
      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable


      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})

      - name: Updating version
        run: sed -i -e 's/^version = .*/version = "${{ steps.get_version.outputs.VERSION }}"/' Cargo.toml

#      - name: Install Protoc
#        uses: arduino/setup-protoc@v1

#      - run: openssl version
      
#      - run: sudo apt-get install nasm

#      - run: cargo install dioxus-cli@0.5.0-alpha.0

#      - run: echo $LD_LIBRARY_PATH

#      - run: sudo apt install build-essential -y
#      - run: sudo apt install libglib2.0-dev -y
#      - run: sudo apt install pkg-config libssl-dev -y
#      - run: sudo apt install libgtk-3-dev -y

#      - run: sudo apt upgrade -y

#      - run: sudo apt update -y

#      - run: sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y

      - run: dx build --platform fullstack --release

  publish:
    runs-on: ubuntu-22.04
    needs: build
    steps:   
      - name: Docker login
        run: |          
          echo "${{ secrets.PUBLISH_TOKEN }}" | docker login https://ghcr.io -u "${{ github.actor }}" --password-stdin   
      - name: Docker Build and Publish
        run: |          
          docker build -t ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }} .
          docker push ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }}
